---
title: "Crop image"
format: html
author: "Davide Risso"
---

# Setup

```{r setup}
library(ImageArray)
library(RBioFormats)
library(ggplot2)
```

# Read tiff image

```{r tiff}
ome.tiff.file <- "../data/TCGA-02-0001-01Z-00-DX1.83fce43e-42ac-4dcd-b156-2908e75f2e47.ome.tiff"
read.metadata(ome.tiff.file)

imgarray <- createImageArray(ome.tiff.file, series = 1, resolution = 1)
imgarray
```

# Crop

```{r crop}
roi <- list(xmin = 4000, ymin = 15000, xmax = 6000, ymax = 18000)

imgarray_sub <- crop(imgarray, index = list(roi$xmin:roi$xmax, roi$ymin:roi$ymax, NULL))

img_raster <- as.raster(imgarray_sub, max.pixel.size = 100)

plot(img_raster)

ggplot(data.frame(x = 0, y = 0), aes(x, y)) +
  coord_fixed(expand = FALSE,
              xlim = c(0, dim(img_raster)[2]),
              ylim = c(0, dim(img_raster)[1])) +
  annotation_raster(img_raster, 
                    0, dim(img_raster)[2],
                    dim(img_raster)[1], 0, interpolate = FALSE)
```

Alternative way: terra.

```{r terra}
library(terra)

rasterized <- rast(ome.tiff.file)
plot(rasterized)

sub_img <- crop(rasterized, ext(roi$xmin, roi$xmax, roi$ymin, roi$ymax))
sub_img

plot(sub_img)
```

# Read zarr image

Let's try to do the same but starting from a Zarr file.

```{r zarr}
library(ZarrArray)
zarr_file <- "../data/TCGA-02-0001-01Z-00-DX1.83fce43e-42ac-4dcd-b156-2908e75f2e47.zarr/images/images/0"

A <- ZarrArray(zarr_file)

img_cropped <- A[1:3, (roi$ymin):(roi$ymax), (roi$xmin):(roi$xmax)]

img_array <- as.array(img_cropped)
img_array <- aperm(img_array, c(2, 3, 1))
sub_img <- rast(img_array)
RGB(sub_img) <- 1:3

plot(sub_img)
```